fullNameOverride: mermin
image:
  repository: mermin
  tag: latest

config:
  # Mermin Default Configuration for Local Development
  # This configuration file contains default settings for the Mermin eBPF network observability tool for local development.
  interface:
    - eth0
  log_level: debug
