[package]
name = "mermin-common"
version = "0.1.0"
edition = "2024"

license.workspace = true

[features]
default = []

[dependencies]
network-types = { path = "../network-types" }

[lib]
path = "src/lib.rs"
