repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        exclude: charts/.*
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false
  - repo: https://github.com/DevinR528/cargo-sort
    rev: v2.0.2
    hooks:
      - id: cargo-sort
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terragrunt-hcl-fmt
