# Consistent parsing between cargo fmt and rustfmt
edition = "2018"
# Consistent formatting between cargo fmt and rustfmt
style_edition = "2024"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
unstable_features = true