{{- if and .Values.rbac.create (empty .Values.rbac.existingClusterRoleName) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "mermin.labels" . | nindent 4 }}
  name: {{ include "mermin.fullname" . }}
rules: []
{{- end }}
