apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "mermin.labels" . | nindent 4 }}
  name: {{ include "mermin.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mermin.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ empty .Values.rbac.existingClusterRoleName | ternary (include "mermin.fullname" .) .Values.rbac.existingClusterRoleName  }}
