[package]
name = "network-types"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
serde = { version = "1", default-features = false, features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]
