nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/elastiflow/mermin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: "10%"
    maxSurge: 0

# Mermin container extra args
extraArgs: []
  # - "--foo"
  # - "bar"

# Extra environment variables
env: []
  # - name: SOME_VAR
  #   value: "SOME_VAL"
  # - name: POD_IP
  #   valueFrom:
  #     fieldRef:
  #       apiVersion: v1
  #       fieldPath: status.podIP
  # - name: "SOME_VAL_FROM_CM"
  #   valueFrom:
  #     configMapKeyRef:
  #       name: cm_name
  #       key: cm_key
  # - name: SOME_VAL_FROM_SECRET
  #   valueFrom:
  #     secretKeyRef:
  #       name: secret_name
  #       key: secret_key

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  automountToken: true

rbac:
  # If false, define the existingClusterRoleName
  create: true
  existingClusterRoleName: ""

# global common labels, applied to all resources
commonLabels: {}

podAnnotations: {}
podLabels: {}

# Enable host networking mode for the pod, incompatible with surge upgrades, may require "dnsPolicy: ClusterFirstWithHostNet"
hostNetwork: false
dnsPolicy: ClusterFirst
hostPID: true

podSecurityContext:
  runAsNonRoot: true

# https://docs.mermin.dev/getting-started/security-considerations
securityContext:
  privileged: true
  readOnlyRootFilesystem: true
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

# TODO(mack#ENG-123|2025-09-29): Set default resources relative to the flows per second
resources:
  limits:
    cpu: 200m
    memory: 220Mi
  requests:
    cpu: 200m
    memory: 220Mi

ports:
  - name: api
    containerPort: 8080
    protocol: TCP
  - name: metrics
    containerPort: 10250
    protocol: TCP

livenessProbe:
  httpGet:
    path: /livez
    port: api
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /readyz
    port: api
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6

startupProbe:
  httpGet:
    path: /startup
    port: api
  initialDelaySeconds: 0
  periodSeconds: 3
  timeoutSeconds: 3
  failureThreshold: 60

# Priority class name for the pod, empty string means no priority class.
# Common value is "system-node-critical" to ensure to schedule the Mermin pods on all nodes.
# See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
priorityClassName: ""

tolerations:
  - effect: NoSchedule
    operator: Exists

affinity: {}

config:
  # Inject config hash to the pod label to force pod restart
  restartOnConfigChange: true

  # If "content" is undefined, default config values are used (empty config)
  # Examples of how to define a custom config:
  # set a custom config via "--set-file config.content=${PATH_RELATIVE_TO_PWD}"
  # Get from file:
  # content: '{{ .Files.Get "config/config.hcl" }}'
  # Define config inline:
  # content: |
  #   log_level = "info"

# Additional volumes for Pods
extraVolumes: []
  # Example:
  # - name: otel-ca-cert
  #   secret:
  #     name: otel-ca-cert

# Additional volume mounts for Pods
extraVolumeMounts: []
  # Example:
  # - name: otel-ca-cert
  #   mountPath: /etc/custom-certs
  #   readOnly: true

# -- Array of extra K8s manifests to deploy (supports templating)
extraObjects: []
  # As a YAML object
  # - apiVersion: secrets-store.csi.x-k8s.io/v1
  #   kind: SecretProviderClass
  #   metadata:
  #     name: '{{ include "mermin.fullname" . }}'
  #   spec:
  #     provider: aws
  #     parameters:
  #       objects: |
  #         - objectName: "argocd"
  #           objectType: "secretsmanager"
  #           jmesPath:
  #               - path: "client_id"
  #                 objectAlias: "client_id"
  #               - path: "client_secret"
  #                 objectAlias: "client_secret"
  #     secretObjects:
  #     - data:
  #       - key: client_id
  #         objectName: client_id
  #       - key: client_secret
  #         objectName: client_secret
  #       secretName: argocd-secrets-store
  #       type: Opaque
  #       labels:
  #         app.kubernetes.io/part-of: argocd
  # # As a YAML string
  # - |
  #   apiVersion: monitoring.googleapis.com/v1
  #   kind: PodMonitoring
  #   metadata:
  #     name: {{ include "mermin.fullname" . }}
  #     namespace: {{ .Release.Namespace }}
  #     labels:
  #       {{- include "mermin.labels" . | nindent 6 }}
  #   spec:
  #     endpoints:
  #     - interval: 60s
  #       port: metrics
  #     selector:
  #       matchLabels:
  #         {{- include "mermin.selectorLabels" . | nindent 6 }}
  #     targetLabels:
  #       metadata:
  #       - pod
  #       - container
