kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mermin-demo
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
#  disableDefaultCNI: true  # If doing 1.2B
  podSubnet: "10.244.0.0/16"
