apiVersion: v2
name: mermin-netobserv-os-stack
description: A Helm chart for deploying the Mermin eBPF agent
icon: https://res.cloudinary.com/elastiflow-cloudinary/image/upload/v1746227898/mermin-horizontal_kxhvzo.png
type: application
version: 0.1.0-beta.2
appVersion: "0.1.0-beta.2"
sources:
  - https://github.com/elastiflow/mermin
dependencies:
  - name: mermin
    # TODO(Cleanup for GA): Should be https://elastiflow.github.io/mermin/, raw.githubusercontent.com... is used whilst repo is private
    # repository: https://elastiflow.github.io/mermin/
    repository: https://raw.githubusercontent.com/elastiflow/mermin/gh-pages
    version: ">= 0.1.0-beta.12"
    condition: mermin.enabled
  - name: netobserv-flow
    repository: https://elastiflow.github.io/helm-chart-netobserv/
    version: ">= 0.4.0"
    condition: netobserv-flow.enabled
  - name: opensearch
    repository: https://opensearch-project.github.io/helm-charts/
    version: ">= 3.3.1"
    condition: opensearch.enabled
  - name: opensearch-dashboards
    repository: https://opensearch-project.github.io/helm-charts/
    version: ">= 3.3.0"
    condition: opensearch-dashboards.enabled
maintainers:
  - name: ElastiFlow Engineering Team
    email: engineering@elastiflow.com
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/elastiflow/mermin
keywords:
  - netflow
  - network
  - flow
  - observability
