name: CI
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: cargo fmt --check
        run: cargo fmt -- --check

  check_and_build:
    name: Check, Lint & Build
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rust-src
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install eBPF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm libelf-dev libz-dev linux-headers-$(uname -r)

      - name: Build eBPF and userspace code
        run: cargo build --release

      - name: Install bpf-linker
        run: cargo install bpf-linker
        
      - name: Lint eBPF code
        run: cargo clippy --package mermin-ebpf -- -D warnings

      - name: Lint userspace code
        run: cargo clippy --all-features -- -D warnings

  test:
    name: Run Tests
    needs: check_and_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install eBPF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm libelf-dev libz-dev make

      - name: Run unit tests
        run: cargo test --release

      - name: Run integration tests
        run: |
          cd network-types/tests
          make clean_test
