---
name: Release Mermin
concurrency:
  group: release-mermin-${{ github.ref }}
  cancel-in-progress: false
on:
  push:
    branches:
      - main
      - alpha
      - beta
    paths-ignore:
      - 'charts/mermin-netobserv-os/**/*'


env:
  BRANCH_TAG_PREFIXES: |
    {
        "alpha": "v0.1.0-alpha.",
        "beta": "v0.1.0-beta.",
        "main": "v"
    }

jobs:
  # Detect if a commit was made from a release PR with title like '[release v0.1.1] (#49)'
  release_or_pr:
    name: Release or Release PR?
    runs-on: ubuntu-latest
    outputs:
      is_release: ${{ steps.release_or_pr.outputs.is_release }}
    steps:
      - id: release_or_pr
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          cat > /tmp/commit_message <<- EOF
          ${COMMIT_MESSAGE}
          EOF
          cat /tmp/commit_message
          # https://regex101.com/r/1z85UX/2
          echo $(grep -Pq '^\[release v(?:[0-9]{1,3}\.?){3}(?:-(?:rc|alpha|beta)(?:\.[0-9]{1,3})?)?\] \(#[0-9]{1,5}\)$' /tmp/commit_message && echo true || echo false) > /tmp/is_release
          echo "is_release=$(cat /tmp/is_release)" >> $GITHUB_OUTPUT

  release_pr_create:
    name: Release PR create
    needs: [release_or_pr]
    if: ${{ ! fromJson(needs.release_or_pr.outputs.is_release) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Prepare Release
        id: prepare_release
        uses: elastiflow/gha-reusable/actions/prepare-release@v0
        with:
          tag_prefix: ${{ fromJson(env.BRANCH_TAG_PREFIXES)[github.ref_name] }}
          exclude_paths: "examples/**/*,charts/mermin-netobserv-os/**/*"
          changelog_update: true
          bump_version_yaml: true
          bump_version_yaml_path: charts/mermin/Chart.yaml
          bump_version_yaml_key: '.version,.appVersion'
      - name: Create Pull Request
        if: ${{ fromJson(steps.prepare_release.outputs.new_release_published) }}
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "${{ github.ref_name }}"
          branch: release-from-${{ github.ref_name }}
          title: '[release v${{ steps.prepare_release.outputs.new_release_version }}]'
          body: |
            # Description
            Release the v${{ steps.prepare_release.outputs.new_release_version }} version

            # Changelog
            ${{ steps.prepare_release.outputs.new_release_notes }}

  release:
    name: Release
    needs: [release_or_pr]
    if: ${{ fromJson(needs.release_or_pr.outputs.is_release) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_release_version: ${{ steps.prepare_release.outputs.new_release_version }}
    env:
      CHARTS_DIR: charts/mermin
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Prepare Release
        id: prepare_release
        uses: elastiflow/gha-reusable/actions/prepare-release@v0
        with:
          tag_prefix: ${{ fromJson(env.BRANCH_TAG_PREFIXES)[github.ref_name] }}
          exclude_paths: "examples/**/*,charts/mermin-netobserv-os/**/*"
          add_git_notes: true
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Install Helm dependencies
        run: |
          (helm dependency list ${{ env.CHARTS_DIR }} || true) | grep -E 'https://' | while read -r dep; do
            helm repo add $(echo ${dep} | awk '{print $1}') $(echo ${dep} | awk '{print $4}')
          done
      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          install_only: true
      - name: Package helm chart
        run: |
          cr package ${{ env.CHARTS_DIR }}
      - name: Create GH release
        if: ${{ fromJson(steps.prepare_release.outputs.new_release_published) }}
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          name: v${{ steps.prepare_release.outputs.new_release_version }}
          tag_name: v${{ steps.prepare_release.outputs.new_release_version }}
          body: |
            ${{ steps.prepare_release.outputs.new_release_notes }}

            Docker images:
            - `ghcr.io/elastiflow/mermin:v${{ steps.prepare_release.outputs.new_release_version }}`
            - `ghcr.io/elastiflow/mermin:v${{ steps.prepare_release.outputs.new_release_version }}-debug`
          target_commitish: ${{ github.ref_name }}
          preserve_order: true
          make_latest: true
          files: ".cr-release-packages/${{ inputs.chart_name }}-*.tgz"
      - name: Update GH pages index
        run: |
          mkdir .cr-index
          cr index --push -t ${{ secrets.GITHUB_TOKEN }} --owner ${{ inputs.repository_owner	}} --git-repo ${{ inputs.repository_name	}}
#

  docker_build_push:
    name: Docker build/push
    needs: [release]
    runs-on: ubuntu-latest-8c
    timeout-minutes: 90
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        target: [runner, runner-debug]
    env:
      TARGET_IMAGE_TAG: |
        {
            "runner": "v${{ needs.release.outputs.new_release_version }}",
            "runner-debug": "v${{ needs.release.outputs.new_release_version }}-debug"
        }
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: google-github-actions/auth@v2
        id: gcr_auth
        with:
          token_format: "access_token"
          project_id: "pub-artifacts-j8rjbu"
          workload_identity_provider: "projects/701687754822/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "gha-registry-writer@pub-artifacts-j8rjbu.iam.gserviceaccount.com"
          access_token_lifetime: 5400s
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcr_auth.outputs.access_token }}
      - name: Build docker image
        uses: elastiflow/gha-reusable/actions/docker-build-push@v0
        with:
          registry: ghcr.io
          image: ${{ github.repository }}
          tag: ${{ fromJson(env.TARGET_IMAGE_TAG)[matrix.target] }}
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.target }}
          push: true
          cache_from: type=registry,ref=us-docker.pkg.dev/pub-artifacts-j8rjbu/docker-cache/mermin-${{ matrix.target }}
          cache_to: type=registry,ref=us-docker.pkg.dev/pub-artifacts-j8rjbu/docker-cache/mermin-${{ matrix.target }},mode=max
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
