name: E2E CNI Tests

on:
  workflow_call:
    inputs:
      cni-list:
        description: 'JSON list of CNIs to test'
        required: false
        default: '["calico", "cilium", "flannel", "kindnetd"]'
        type: string
      test-path:
        description: 'path the the e2e test suite that should be run'
        required: true
        type: string
      image-tag:
        description: 'Tag of the Mermin image to use for testing'
        required: false
        default: 'latest'
        type: string


jobs:
  build:
    name: Build Mermin Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: google-github-actions/auth@v2
        id: gcr_auth
        with:
          token_format: "access_token"
          project_id: "pub-artifacts-j8rjbu"
          workload_identity_provider: "projects/701687754822/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "gha-registry-writer@pub-artifacts-j8rjbu.iam.gserviceaccount.com"

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcr_auth.outputs.access_token }}

      - name: Build docker image
        uses: elastiflow/gha-reusable/actions/docker-build-push@v0
        with:
          image: mermin
          tag: ${{ inputs.image-tag }}
          platforms: linux/amd64
          target: runner-debug
          load: true
          cache_from: type=registry,ref=us-docker.pkg.dev/pub-artifacts-j8rjbu/docker-cache/mermin-ci-runner-debug-linux/amd64
          cache_to: type=registry,ref=us-docker.pkg.dev/pub-artifacts-j8rjbu/docker-cache/mermin-ci-runner-debug-linux/amd64,mode=max

      - name: Save Docker image as an artifact
        run: |
          mkdir -p image-artifact
          docker save not-exists.elastiflow.com/mermin:${{ inputs.image-tag }} -o image-artifact/mermin-${{ inputs.image-tag }}.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: mermin-docker-image-${{ inputs.image-tag }}
          path: image-artifact/

  cni-integration-test:
    name: ${{ matrix.cni }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cni: ${{ fromJson(inputs.cni-list) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go for Cilium CLI install
        if: matrix.cni == 'cilium'
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: mermin-docker-image-${{ inputs.image-tag }}
          path: image-artifact/

      - name: Load Docker image
        run: docker load < image-artifact/mermin-${{ inputs.image-tag }}.tar

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Add Homebrew to PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Install gRPCurl
        run: brew install grpcurl

      - name: Make test script executable
        run: chmod +x ${{ inputs.test-path }}

      - name: Run E2E Test for ${{ matrix.cni }}
        env:
          CNI: ${{ matrix.cni }}
          DOCKER_REPOSITORY: not-exists.elastiflow.com/mermin
          DOCKER_IMAGE_TAG: ${{ inputs.image-tag }}
          HOST_DOCKER_INTERNAL_ADDR: 172.17.0.1
          MERMIN_CONFIG_PATH: docs/deployment/examples/local/config.example.hcl
        run: ${{ inputs.test-path }}
