name: E2E CNI Tests

on:
  workflow_call:
    inputs:
      cni-list:
        description: 'JSON list of CNIs to test'
        required: false
        default: '["calico", "cilium", "flannel", "kindnetd"]'
        type: string

jobs:
  build:
    name: Build Mermin Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: google-github-actions/auth@v2
        id: gcr_auth
        with:
          token_format: "access_token"
          project_id: "pub-artifacts-j8rjbu"
          workload_identity_provider: "projects/701687754822/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "gha-registry-writer@pub-artifacts-j8rjbu.iam.gserviceaccount.com"

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcr_auth.outputs.access_token }}

      - name: Build docker image
        uses: elastiflow/gha-reusable/actions/docker-build-push@v0
        with:
          image: mermin
          tag: latest
          platforms: linux/amd64
          target: runner-debug
          load: true
          cache_from: type=registry,ref=us-docker.pkg.dev/pub-artifacts-j8rjbu/docker-cache/mermin-runner-debug
          cache_to: type=registry,ref=us-docker.pkg.dev/pub-artifacts-j8rjbu/docker-cache/mermin-runner-debug,mode=max

      - name: Save Docker image as an artifact
        run: |
          mkdir -p image-artifact
          docker save not-exists.elastiflow.com/mermin:latest -o image-artifact/mermin-latest.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: mermin-docker-image
          path: image-artifact/

  cni-integration-test:
    name: ${{ matrix.cni }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cni: ${{ fromJson(inputs.cni-list) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go for Cilium CLI install
        if: matrix.cni == 'cilium'
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: mermin-docker-image
          path: image-artifact/

      - name: Load Docker image
        run: docker load < image-artifact/mermin-latest.tar

      - name: Make test script executable
        run: chmod +x ./test_cni.sh

      - name: Run E2E Test for ${{ matrix.cni }}
        env:
          CNI: ${{ matrix.cni }}
          DOCKER_IMAGE_NAME: not-exists.elastiflow.com/mermin
        run: ./test_cni.sh
